### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by JacopoDaeli** [InstantWebP2P/electron-httpp#1]
Hello guys, any update about the status the project?
I am trying to understand how to start with. I need udt with electron and I was wondering how to do it.

Thanks

**Comment by sequoiar** [comment]
@JacopoDaeli you can saw I created another project named electron-node-httpp. so, the first step is have electron using node-httpp as nodejs/iojs basis. then, porting Electron to use electron-node-httpp. 
I will start electron-node-httpp after couple of monthes.

**Comment by JacopoDaeli** [comment]
@sequoiar cool. Does this means we have to wait? Or is there a way to compile today the project and use it already?

**Comment by sequoiar** [comment]
it's in my plan.

**Comment by JacopoDaeli** [comment]
:-) What about create a native-udt4 nodejs module? Do you know if something exists already? This one seems gone https://www.npmjs.com/package/udt4

**Comment by sequoiar** [comment]
it's not easy to bind udt4 as native module, due to udt4's multi-thread/timer complexity.

**Comment by JacopoDaeli** [comment]
@sequoiar is the project still going?

**Comment by sequoiar** [comment]
@JacopoDaeli sure. the plan is upgrade node-httpp to nodejs mainline firstly, then merge to electoron-httpp.
